// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/autothresholdr.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// mean_pillars
NumericMatrix mean_pillars(NumericVector arr3d);
static SEXP autothresholdr_mean_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_mean_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_mean_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// var_pillars
NumericMatrix var_pillars(NumericVector arr3d);
static SEXP autothresholdr_var_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(var_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_var_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_var_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// median_pillars
NumericMatrix median_pillars(NumericVector arr3d);
static SEXP autothresholdr_median_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(median_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_median_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_median_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int autothresholdr_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericMatrix(*mean_pillars)(NumericVector)");
        signatures.insert("NumericMatrix(*var_pillars)(NumericVector)");
        signatures.insert("NumericMatrix(*median_pillars)(NumericVector)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP autothresholdr_RcppExport_registerCCallable() { 
    R_RegisterCCallable("autothresholdr", "autothresholdr_mean_pillars", (DL_FUNC)autothresholdr_mean_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_var_pillars", (DL_FUNC)autothresholdr_var_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_median_pillars", (DL_FUNC)autothresholdr_median_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_RcppExport_validate", (DL_FUNC)autothresholdr_RcppExport_validate);
    return R_NilValue;
}
