// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/autothresholdr.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// IJDefault
int IJDefault(IntegerVector data);
RcppExport SEXP autothresholdr_IJDefault(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(IJDefault(data));
    return rcpp_result_gen;
END_RCPP
}
// Huang
int Huang(IntegerVector data);
RcppExport SEXP autothresholdr_Huang(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Huang(data));
    return rcpp_result_gen;
END_RCPP
}
// Huang2
int Huang2(IntegerVector data);
RcppExport SEXP autothresholdr_Huang2(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Huang2(data));
    return rcpp_result_gen;
END_RCPP
}
// Intermodes
int Intermodes(IntegerVector data);
RcppExport SEXP autothresholdr_Intermodes(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Intermodes(data));
    return rcpp_result_gen;
END_RCPP
}
// IsoData
int IsoData(IntegerVector data);
RcppExport SEXP autothresholdr_IsoData(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(IsoData(data));
    return rcpp_result_gen;
END_RCPP
}
// Li
int Li(IntegerVector data);
RcppExport SEXP autothresholdr_Li(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Li(data));
    return rcpp_result_gen;
END_RCPP
}
// MaxEntropy
int MaxEntropy(IntegerVector data);
RcppExport SEXP autothresholdr_MaxEntropy(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(MaxEntropy(data));
    return rcpp_result_gen;
END_RCPP
}
// Mean
int Mean(IntegerVector data);
RcppExport SEXP autothresholdr_Mean(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Mean(data));
    return rcpp_result_gen;
END_RCPP
}
// MinErrorI
int MinErrorI(IntegerVector data);
RcppExport SEXP autothresholdr_MinErrorI(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(MinErrorI(data));
    return rcpp_result_gen;
END_RCPP
}
// Minimum
int Minimum(IntegerVector data);
RcppExport SEXP autothresholdr_Minimum(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Minimum(data));
    return rcpp_result_gen;
END_RCPP
}
// Moments
int Moments(IntegerVector data);
RcppExport SEXP autothresholdr_Moments(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Moments(data));
    return rcpp_result_gen;
END_RCPP
}
// Otsu
int Otsu(IntegerVector data);
RcppExport SEXP autothresholdr_Otsu(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Otsu(data));
    return rcpp_result_gen;
END_RCPP
}
// Percentile
int Percentile(IntegerVector data);
RcppExport SEXP autothresholdr_Percentile(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Percentile(data));
    return rcpp_result_gen;
END_RCPP
}
// RenyiEntropy
int RenyiEntropy(IntegerVector data);
RcppExport SEXP autothresholdr_RenyiEntropy(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(RenyiEntropy(data));
    return rcpp_result_gen;
END_RCPP
}
// Shanbhag
int Shanbhag(IntegerVector data);
RcppExport SEXP autothresholdr_Shanbhag(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Shanbhag(data));
    return rcpp_result_gen;
END_RCPP
}
// Triangle
int Triangle(IntegerVector data);
RcppExport SEXP autothresholdr_Triangle(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Triangle(data));
    return rcpp_result_gen;
END_RCPP
}
// Yen
int Yen(IntegerVector data);
RcppExport SEXP autothresholdr_Yen(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(Yen(data));
    return rcpp_result_gen;
END_RCPP
}
// sum_pillars
NumericMatrix sum_pillars(NumericVector arr3d);
static SEXP autothresholdr_sum_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_sum_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_sum_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// mean_pillars
NumericMatrix mean_pillars(NumericVector arr3d);
static SEXP autothresholdr_mean_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_mean_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_mean_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// var_pillars
NumericMatrix var_pillars(NumericVector arr3d);
static SEXP autothresholdr_var_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(var_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_var_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_var_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// median_pillars
NumericMatrix median_pillars(NumericVector arr3d);
static SEXP autothresholdr_median_pillars_try(SEXP arr3dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type arr3d(arr3dSEXP);
    rcpp_result_gen = Rcpp::wrap(median_pillars(arr3d));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP autothresholdr_median_pillars(SEXP arr3dSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(autothresholdr_median_pillars_try(arr3dSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int autothresholdr_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericMatrix(*sum_pillars)(NumericVector)");
        signatures.insert("NumericMatrix(*mean_pillars)(NumericVector)");
        signatures.insert("NumericMatrix(*var_pillars)(NumericVector)");
        signatures.insert("NumericMatrix(*median_pillars)(NumericVector)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP autothresholdr_RcppExport_registerCCallable() { 
    R_RegisterCCallable("autothresholdr", "autothresholdr_sum_pillars", (DL_FUNC)autothresholdr_sum_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_mean_pillars", (DL_FUNC)autothresholdr_mean_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_var_pillars", (DL_FUNC)autothresholdr_var_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_median_pillars", (DL_FUNC)autothresholdr_median_pillars_try);
    R_RegisterCCallable("autothresholdr", "autothresholdr_RcppExport_validate", (DL_FUNC)autothresholdr_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"autothresholdr_IJDefault", (DL_FUNC) &autothresholdr_IJDefault, 1},
    {"autothresholdr_Huang", (DL_FUNC) &autothresholdr_Huang, 1},
    {"autothresholdr_Huang2", (DL_FUNC) &autothresholdr_Huang2, 1},
    {"autothresholdr_Intermodes", (DL_FUNC) &autothresholdr_Intermodes, 1},
    {"autothresholdr_IsoData", (DL_FUNC) &autothresholdr_IsoData, 1},
    {"autothresholdr_Li", (DL_FUNC) &autothresholdr_Li, 1},
    {"autothresholdr_MaxEntropy", (DL_FUNC) &autothresholdr_MaxEntropy, 1},
    {"autothresholdr_Mean", (DL_FUNC) &autothresholdr_Mean, 1},
    {"autothresholdr_MinErrorI", (DL_FUNC) &autothresholdr_MinErrorI, 1},
    {"autothresholdr_Minimum", (DL_FUNC) &autothresholdr_Minimum, 1},
    {"autothresholdr_Moments", (DL_FUNC) &autothresholdr_Moments, 1},
    {"autothresholdr_Otsu", (DL_FUNC) &autothresholdr_Otsu, 1},
    {"autothresholdr_Percentile", (DL_FUNC) &autothresholdr_Percentile, 1},
    {"autothresholdr_RenyiEntropy", (DL_FUNC) &autothresholdr_RenyiEntropy, 1},
    {"autothresholdr_Shanbhag", (DL_FUNC) &autothresholdr_Shanbhag, 1},
    {"autothresholdr_Triangle", (DL_FUNC) &autothresholdr_Triangle, 1},
    {"autothresholdr_Yen", (DL_FUNC) &autothresholdr_Yen, 1},
    {"autothresholdr_sum_pillars", (DL_FUNC) &autothresholdr_sum_pillars, 1},
    {"autothresholdr_mean_pillars", (DL_FUNC) &autothresholdr_mean_pillars, 1},
    {"autothresholdr_var_pillars", (DL_FUNC) &autothresholdr_var_pillars, 1},
    {"autothresholdr_median_pillars", (DL_FUNC) &autothresholdr_median_pillars, 1},
    {"autothresholdr_RcppExport_registerCCallable", (DL_FUNC) &autothresholdr_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_autothresholdr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
